#include "px4_offboard_controllers/controllers/lee.hpp"
#include <cmath>
#include <stdexcept>
namespace px4_offboard { namespace {
struct UnitKinematics{Vec3 value,first,second;};
UnitKinematics normalizeWithDerivatives(const Vec3&v,const Vec3&vd,const Vec3&vdd){double r=v.norm();if(!(r>kEps)||!std::isfinite(r))throw std::invalid_argument("desired direction is singular");Vec3 b=v/r;double rd=dot(b,vd);Vec3 bd=(vd-b*rd)/r;double rdd=dot(bd,vd)+dot(b,vdd);Vec3 bdd=(vdd-2.0*bd*rd-b*rdd)/r;return{b,bd,bdd};}
struct DesiredKinematics{Mat3 rotation,rotation_dot,rotation_ddot;Vec3 body_rate,body_angular_accel;};
DesiredKinematics desiredKinematics(const Vec3&f,const Vec3&fd,const Vec3&fdd,double yaw,double yr,double ya){auto b3=normalizeWithDerivatives(-f,-fd,-fdd);Vec3 b1c{std::cos(yaw),std::sin(yaw),0};Vec3 b1cd{-std::sin(yaw)*yr,std::cos(yaw)*yr,0};Vec3 b1cdd{-std::cos(yaw)*yr*yr-std::sin(yaw)*ya,-std::sin(yaw)*yr*yr+std::cos(yaw)*ya,0};Vec3 c=cross(b3.value,b1c),cd=cross(b3.first,b1c)+cross(b3.value,b1cd),cdd=cross(b3.second,b1c)+2.0*cross(b3.first,b1cd)+cross(b3.value,b1cdd);auto b2=normalizeWithDerivatives(c,cd,cdd);Vec3 b1=cross(b2.value,b3.value),b1d=cross(b2.first,b3.value)+cross(b2.value,b3.first),b1dd=cross(b2.second,b3.value)+2.0*cross(b2.first,b3.first)+cross(b2.value,b3.second);DesiredKinematics o{};o.rotation=rotationFromColumns(b1,b2.value,b3.value);o.rotation_dot=rotationFromColumns(b1d,b2.first,b3.first);o.rotation_ddot=rotationFromColumns(b1dd,b2.second,b3.second);o.body_rate=vee(skew(o.rotation.transpose()*o.rotation_dot));o.body_angular_accel=vee(skew(o.rotation.transpose()*o.rotation_ddot));return o;}
bool positive(const Vec3&v){return v.finite()&&v.x>0&&v.y>0&&v.z>0;} bool validInertia(const Mat3&i){if(!i.finite())return false;constexpr double t=1e-12;if(std::abs(i(0,1)-i(1,0))>t||std::abs(i(0,2)-i(2,0))>t||std::abs(i(1,2)-i(2,1))>t)return false;double m1=i(0,0),m2=i(0,0)*i(1,1)-i(0,1)*i(1,0),m3=determinant(i);return m1>kEps&&m2>kEps&&m3>kEps;}
}
LeeController::LeeController(LeeConfig c):config_(c){if(!(c.mass_kg>0)||!std::isfinite(c.mass_kg)||!(c.gravity_mps2>0)||!std::isfinite(c.gravity_mps2)||!positive(c.k_position)||!positive(c.k_velocity)||!positive(c.k_attitude)||!positive(c.k_rate)||!validInertia(c.inertia_kgm2))throw std::invalid_argument("invalid Lee controller configuration");}
LeeOutput LeeController::update(const CanonicalState&s,const TrajectoryReference&r)const{if(!validateState(s,requirementsFor(ControllerKind::LeeWrench))||!validateReference(r,ReferenceProfile::LeeFull))throw std::invalid_argument("invalid Lee controller state/reference");const Vec3 x=s.position_ned->value,v=s.velocity_ned->value,omega=s.body_rate_frd->value;const Mat3 R=s.attitude_ned_frd->value.normalized().toMat3();LeeOutput o{};o.position_error_ned_m=x-*r.position;o.velocity_error_ned_mps=v-*r.velocity;const Vec3 e3{0,0,1};o.force_ned_n=-hadamard(config_.k_position,o.position_error_ned_m)-hadamard(config_.k_velocity,o.velocity_error_ned_mps)-config_.mass_kg*config_.gravity_mps2*e3+config_.mass_kg*(*r.acceleration);Vec3 bz=R*e3;o.collective_thrust_n=-dot(o.force_ned_n,bz);Vec3 accel=config_.gravity_mps2*e3-(o.collective_thrust_n/config_.mass_kg)*bz;Vec3 evd=accel-*r.acceleration;Vec3 bzd=R*cross(omega,e3);Vec3 fd=-hadamard(config_.k_position,o.velocity_error_ned_mps)-hadamard(config_.k_velocity,evd)+config_.mass_kg*(*r.jerk);double td=-(dot(fd,bz)+dot(o.force_ned_n,bzd));Vec3 jerk=-(td/config_.mass_kg)*bz-(o.collective_thrust_n/config_.mass_kg)*bzd;Vec3 evdd=jerk-*r.jerk;Vec3 fdd=-hadamard(config_.k_position,evd)-hadamard(config_.k_velocity,evdd)+config_.mass_kg*(*r.snap);auto d=desiredKinematics(o.force_ned_n,fd,fdd,*r.yaw,*r.yaw_rate,*r.yaw_accel);o.desired_rotation_ned_frd=d.rotation;o.desired_rotation_dot=d.rotation_dot;o.desired_rotation_ddot=d.rotation_ddot;o.desired_body_z_ned=d.rotation.column(2);o.desired_body_rate_frd_radps=d.body_rate;o.desired_body_angular_accel_frd_radps2=d.body_angular_accel;o.attitude_error=.5*vee(d.rotation.transpose()*R-R.transpose()*d.rotation);Vec3 wd=R.transpose()*d.rotation*d.body_rate;o.rate_error_frd_radps=omega-wd;Vec3 jomega=config_.inertia_kgm2*omega;Vec3 inside=cross(omega,wd)-R.transpose()*d.rotation*d.body_angular_accel;o.body_moment_frd_nm=-hadamard(config_.k_attitude,o.attitude_error)-hadamard(config_.k_rate,o.rate_error_frd_radps)+cross(omega,jomega)-config_.inertia_kgm2*inside;return o;}
}
